'use client'
import Head from "next/head"
import { useSession } from "next-auth/react"
import { useRouter } from "next/router"
import NavBar from "../../src/components/NavBar"
import { Eye, FilePlus2, Pencil, User } from "lucide-react"
import Link from "next/link"
import { unstable_getServerSession } from "next-auth"
import { authOptions } from "../api/auth/[...nextauth]"
import prisma from "../../src/db/prisma"

export async function getServerSideProps({ req, res }) {

  const session = await unstable_getServerSession(req, res, authOptions)
  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  } else if(session.user.role !== "admin") {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  const userData = await prisma.User.findUnique({
    where: { id: session.user.id },
  })

  return {
    props: {
      userData
    },
  }
}
export default function MainPage({ userData }) {
  const router = useRouter()
  const { status, data: session } = useSession()


  if (status === "unauthenticated") {
    void router.push("/login")
    return null
  }

  if (status === "loading") return <div>Loading...</div>

  return <Page userData={userData} />
}

function Page({ userData }) {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Admin Panel </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='spreadsheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css'
        />
      </Head>

      <main className=''>
        <div className=''>
          <NavBar />
        </div>
        <div className='m-7'>
          <a
            className='text-center w-32 h-auto font-bold justify-self-center flex flex-col items-center p-2 border drop-shadow-xl rounded-2xl text-black bg-gray-50 hover:bg-gray-200'
            href='Admin/EditAdmin'
          >
            {userData?.image ?
              <img
                className='rounded-2xl bg-contain'
                src={userData?.image ? '/uploads/' + userData.image : ""}
                width={100}
                height={100}
                alt='images'
              />
              :
              <User className='text-center h-16 capitalize' />
            }
            {userData.name}
          </a>
        </div>

        {/* Dashboard */}
        <div className='mt-10'>
          <h2 className='m-7 text-2xl font-bold'> Dashboard </h2>{" "}
          <div className='md:flex-row m-7 flex flex-col flex-wrap gap-3'>
            {/* Styled Funtion */}
            <Link
              className='font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Admin/hospital'
            >
              <FilePlus2 className='text-center' />
              Hospitals
            </Link>

            <Link
              className='font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Admin/department'
            >
              <Pencil className='text-center' />
              Departments
            </Link>

            <Link
              className='font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Admin/doctor/new'
            >
              <Eye className='text-center' />
              Register Doctor
            </Link>

            <Link
              className='font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Admin/EditAdmin'
            >
              <Eye className='text-center' />
              Edit Profile
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
