import Head from "next/head"
import Button from "../../components/ui/Button"

export default function MainPage() {
  return (
    <>
      <Head>
        <title>Welcome Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='stylesheet' href='./styles/style.css' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
        />
      </Head>

      <main className=''>
        <div className='bg-black'>
          <nav className='flex space-x-6 md:space-x-96 px-10 py-5 text-white font-bold mx-[100px]'>
            <div>
              <a href='' class=''>
                HCS
              </a>
            </div>

            <div className='flex'>
              <ul className='flex space-x-3 md:space-x-10'>
                <li class=''>
                  <a href='' class=''>
                    Log Out
                  </a>
                </li>
              </ul>
            </div>
          </nav>
        </div>

        <div className='p-10 '>
          <h1> Welcome Doctor!!! </h1>
        </div>

        <div className='m-7'>
          <h2> Dashboard </h2>{" "}
        </div>

        <div className='flex gap-1 m-7'>
          <Button className='group relative flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2'>
            <a href='question'> Answer the Questions </a>
          </Button>

          <Button className='group relative flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2'>
            <a href='info-dynamic/new'> Add Information to Blog </a>
          </Button>

          <Button className='group relative flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2'>
            <a href='info-dynamic'> View Blog Information </a>
          </Button>
        </div>
      </main>
    </>
  )
}
