import Head from "next/head"
import Button from "../../components/ui/Button"
import { useSession, signOut } from "next-auth/react"
import { useRouter } from "next/router"
import NavBar from "../../src/components/NavBar"
import { BookOpen, Eye, FilePlus2, Pencil, User } from "lucide-react"
import Link from "next/link"
import { unstable_getServerSession } from "next-auth"
import { authOptions } from "../api/auth/[...nextauth]"


export async function getServerSideProps({ req, res }) {

  const session = await unstable_getServerSession(req, res, authOptions)
  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  } else if (session.user.role !== "doctor") {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  const userData = await prisma.User.findUnique({
    where: { id: session.user.id },
    include: {
      Doctor: true
    }
  })

  return {
    props: {
      userData: JSON.parse(JSON.stringify(userData.Doctor[0] || []))
    },
  }
}
export default function MainPage({ userData }) {
  const router = useRouter()
  const { status, data: session } = useSession()

  
  if (status === "unauthenticated") {
    router.push("/login")
    return null
  }
  
  if (status === "loading") return <div>Loading...</div>
  return <Page userData={userData} />
}

function Page({ userData }) {
  console.log(userData, "@@@");
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Welcome Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='spreadsheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css'
        />
      </Head>

      <main className=''>
        <div className=''>
          <NavBar />
        </div>
        <div className='m-7'>
          <Link
            className='text-center w-40 h-auto font-bold justify-self-center flex flex-col items-center px-4 py-4 border drop-shadow-xl rounded-2xl text-black bg-gray-50 hover:bg-gray-200'
            href='Doctor/profile'
          >
            {userData?.image ?
              <img
              className='rounded-2xl bg-contain w-40'
                src={userData?.image ? '/uploads/' + userData.image : ""}
                width={100}
                height={100}
                alt='images'
              />
              :
              <User className='text-center h-16 capitalize' />
            }
            <span className='mt-2'>Dr. {userData.name}</span>
          </Link>
        </div>

        {/* Dashboard */}
        <div className='mt-10'>
          <h2 className='m-7 text-2xl font-bold'> Dashboard </h2>{" "}
          <div className='md:flex-row m-7 flex flex-col flex-wrap gap-3'>
            {/* Styled Funtion */}
            <Link
              className='w-full sm:w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Doctor/question'
            >
              <Pencil className='text-center' />
              Answer the Questions
            </Link>

            <Link
              className='w-full sm:w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Doctor/info-dynamic/new'
            >
              <FilePlus2 className='text-center' />
              Add Information to Blog
            </Link>

            <Link
              className='w-full sm:w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Doctor/info-dynamic'
            >
              <Eye className='text-center' />
              View Blog Information
            </Link>
            <Link
              className='w-full sm:w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Doctor/schedule-appoinment'
            >
              <Eye className='text-center' />
              Schedule appoinment
            </Link>
            <Link
              className='w-full sm:w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Doctor/EditDoctor'
            >
              <Eye className='text-center' />
              Edit Profile
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
