import Head from "next/head"
import Button from "../../components/ui/Button"
import { NextPage } from "next"
import { useSession, signOut } from "next-auth/react"
import { useRouter } from "next/router"
import NavBar from "../../src/components/NavBar"
import {
  Book,
  Contact,
  FilePlus2,
  HelpCircle,
  Pencil,
  User,
  File,
  Syringe,
} from "lucide-react"
import { useEffect } from "react"
import axios from "axios"

export default function MainPage() {
  const router = useRouter()
  const { status, data: session } = useSession()

  if (status === "loading") return <div>Loading...</div>

  if (status === "unauthenticated") {
    router.push("/login")
    return null
  }

  console.log(session)
  if (session.user.role === "doctor") {
    void router.push("/Doctor")
    return null
  }

  return <Page />
}

function Page() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Welcome Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <div className=''>
          <NavBar />
        </div>
        <div className='m-7'>
          <a
            className='text-center w-32 h-32 font-bold justify-self-center flex flex-col items-center px-4 py-4 border drop-shadow-xl rounded-full text-black bg-gray-50 hover:bg-gray-200'
            href='Patients/profile'
          >
            <User className='text-center h-16 capitalize' />
            {session.user.name}
          </a>
        </div>

        {/* Dashboard */}
        <div className='mt-10'>
          <h2 className='m-7 text-2xl font-bold'> Dashboard </h2>{" "}
          <h2 className='text-xl font-bold pl-6'> Function Section </h2>
          <div className='md:flex-row m-7 flex flex-col flex-wrap gap-3'>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Appointment'
            >
              <Syringe className='text-center' />
              Create Appointment
            </a>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Patients/question/new'
            >
              <Syringe className='text-center' />
              Consult Doctor
            </a>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Patients/report-next'
            >
              <FilePlus2 className='text-center' />
              Add Report
            </a>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Patients/doctors'
            >
              <Contact className='text-center' />
              Doctors Contact
            </a>
          </div>
          {/* Next Line */}
          <h2 className='text-xl font-bold pl-6 mt-6'> Information Section </h2>
          <div className='md:flex-row m-7 flex flex-col flex-wrap gap-3'>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='Patients/question'
            >
              <HelpCircle className='text-center' />
              View Q/A
            </a>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Patients/report-next/img-get'
            >
              <File className='text-center' />
              View Reports
            </a>
            <a
              className='w-[300px] font-bold justify-self-center flex flex-col gap-4 items-center px-10 py-20 border drop-shadow-xl rounded-md text-blue-800 bg-white hover:bg-indigo-600 hover:text-white'
              href='/Patients/info-dynamic'
            >
              <Book className='text-center' />
              View Blog
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
