import Head from "next/head"
import Members from "../components/Home/Members"
import Footer from "../src/components/Footer"
import NavBar from "../src/components/NavBar"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <div className=''>
          <div className=''>
            <NavBar />
          </div>

          <div className='py-5 mt-12'>
            <h1 className='text-3xl font-bold text-center'>ABOUT US!</h1>

            <div className='flex flex-col py-5 px-10 sec-leader md:flex-row'>
              <div className='basis-1/2 '>
                <img
                  src='images/asmita.jpg'
                  alt='man'
                  className='w-full'
                  max-height='200px'
                  width='auto'
                ></img>
              </div>

              <div className='basis-1/2 text-center bg-[#ccc7da] px-5 py-3 '>
                <h2 className='font-bold text-2xl '> Iccha Pandey </h2>
                <p className='text-left my-5 '>
                  Iccha is the CEO of our company. She is a hardworking and
                  talented person. She has double bachelors degree.She is a
                  hardworking and talented person. She has a degree in Business
                  Administration. She also has two years experience in the
                  health field. She wanted to work in the health sector since
                  early childhood. Her mother used to be ill sometimes. At that
                  point in time she thought to found an organisation and work
                  for the good cause of the people.
                </p>
              </div>
            </div>

            <div className='py-10 px-5'>
              <h2 className='font-bold text-2xl text-center'>OTHER MEMBERS</h2>

              <Members />
            </div>
            <div>
              <Footer />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
