import Head from "next/head"
import Members from "../components/Home/Members"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='stylesheet' href='./styles/style.css' />
      </Head>

      <main className=''>
        <div className=''>
          <div className='bg-black'>
            <nav className='flex space-x-6 md:space-x-96 px-10 py-5 text-white font-bold mx-[100px]'>
              <div>
                <a href='' class=''>
                  HCS
                </a>
              </div>

              <div className='flex'>
                <ul className='flex space-x-3 md:space-x-10'>
                  <li class=''>
                    <a href='/' class=''>
                      Home
                    </a>
                  </li>

                  <li class=''>
                    <a href='/about-us' class=''>
                      About
                    </a>
                  </li>

                  <li class=''>
                    <a href='/info' class=''>
                      Information
                    </a>
                  </li>
                  <li class=''>
                    <a href='/register' class=''>
                      Sign In/Log In
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
          </div>

          <div className='py-5'>
            <h1 className='text-3xl font-bold text-center'>ABOUT US!</h1>

            <div className='flex flex-col py-5 px-10 sec-leader md:flex-row'>
              <div className='basis-1/2 '>
                <img src='images/man.jpg' alt='man' className='w-full'></img>
              </div>

              <div className='basis-1/2 text-center bg-[#C4BBDF] px-5 py-3 '>
                <h2 className='font-bold text-2xl '> Adam Jonas </h2>
                <p className='text-left my-5 '>
                  Adam is the CEO of our company. He is a hardworking and
                  talented person. He has double bachelors degree.He is a
                  hardworking and talented person. He has double bachelors
                  degree.He is a hardworking and talented person. He has double
                  bachelors degree.
                </p>
              </div>
            </div>

            <div className='py-10 px-5'>
              <h2 className='font-bold text-2xl text-center'>OTHER MEMBERS</h2>

              <Members />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
