import Head from "next/head"
import Features from "../components/Home/features"
import Button from "../components/ui/Button"

export default function MainPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='stylesheet' href='./styles/style.css' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
        />
      </Head>

      <main className=''>
        <div>
          <div class='bg-black'>
            <nav className='flex space-x-6 md:space-x-96 px-10 py-5 text-white font-bold mx-[100px]'>
              <div>
                <a href='' class=''>
                  HCS
                </a>
              </div>

              <div className='flex'>
                <ul className='flex space-x-3 md:space-x-10'>
                  <li class=''>
                    <a href='' class=''>
                      Home
                    </a>
                  </li>

                  <li class=''>
                    <a href='/about-us' class=''>
                      About
                    </a>
                  </li>

                  <li class=''>
                    <a href='/info-dynamic' class=''>
                      Information
                    </a>
                  </li>

                  <li class=''>
                    <a href='/register' class=''>
                      Sign In/Log In
                    </a>
                  </li>
                </ul>
              </div>
            </nav>

            <div className='px-28 py-28'>
              <div className='text-center font-bold text-white'>
                <h1 className='text-xl md:text-2xl'>
                  Health Consultation System{" "}
                </h1>
                <h2 className='text-600 md:text-lg'>
                  {" "}
                  Get a professional Medical Advice{" "}
                </h2>

                <h5>
                  <a href='/question' class=''>
                    Ask a Question? Get an Answer
                  </a>
                </h5>
              </div>
            </div>
          </div>

          <div className='p-12 md:p-24'>
            <h2 className='text-xl md:text-2xl text-center'>
              Professionals here advertise the best one they know
            </h2>
            <p className='py-[20px] text-500 md:text-lg max-w-5xl '>
              In this world where it is difficult to trust professionals, here
              you can ask professionals suggestions and international suggestion
              for the cure and not just temporary recovary. In this world where
              it is difficult to trust professionals ask professionals
            </p>
          </div>

          <div className='main-features'>
            <div className='py-10 px-5'>
              <h2 className='font-bold text-2xl text-center'>Main Features </h2>

              <Features />
            </div>
          </div>

          <section>
            <div className='m-[100px] p-[50px] text-center flex flex-wrap gap-5 justify-center bg-blue-200 rounded-md'>
              <h3 className='font-bold text-2xl'> Are you Ready? </h3>
              <p class=''>
                Get to explore the world of accurate information in Health and
                Science. Make the right decison for your health or for the
                health of someone you really care.
              </p>

              <Button>
                <a href='register'> Create an Account! </a>
              </Button>
            </div>
          </section>
        </div>
      </main>
    </>
  )
}
